import "./globals.css";
import Header from "@/components/Header";
import {
  ClerkProvider,
} from '@clerk/nextjs'


export const metadata = {
  title: "pamphlet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html  lang="en">
        
        <body  className="">
          <Header/>
          {children}
        </body>
        
        
      </html>
    </ClerkProvider>
  );
}
